#!/bin/sh
set -ev

export UUID=$(cat /proc/sys/kernel/random/uuid)

if [ -n "$ECS_CONTAINER_METADATA_URI_V4" ]; then
    ARK_HOST="$(curl -sf "$ECS_CONTAINER_METADATA_URI_V4" | jq -r '.Networks[0].IPv4Addresses[0]')"
    export ARK_HOST
fi

/bin/env_parse ${SERVER_CONFIG}.j2

/bin/env_parse ${SECONDARY_CONFIG}.j2

exec su socrata -c 'exec /usr/bin/java \
    -Xmx${JAVA_XMX} \
    -Xms${JAVA_XMX} \
    -Dconfig.file=${SERVER_ROOT}/${SERVER_CONFIG} \
    -Djava.net.preferIPv4Stack=true \
    -Dcom.sun.management.jmxremote.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.rmi.port=${JMX_PORT} \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Djava.rmi.server.hostname=${ARK_HOST:-localhost} \
    -Dcom.socrata.data-coordinator.secondary-watcher.log4j.rootLogger.0=${LOG_LEVEL:-INFO} \
    -XX:MaxMetaspaceSize=${JAVA_MAX_METASPACE} \
    -XX:+ExitOnOutOfMemoryError \
    -jar $SERVER_ARTIFACT
    '
